version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/server.conf
  php7:
    image: php:7-fpm-alpine
    volumes:
      - ./www:/var/www/html
